// Generated by `geam embedding sync`. Do not edit.

use geam::HostComponentProfile;
use geam::HostProfile;
use geam::HostProviderComponent;
use geam::HostProviderComponentInitialization;
use geam::HostProviderComponentRegistration as ComponentRegistration;
use geam::HostProviderConfiguration;
use geam::HostProviderInitializationError;
use geam::HostProviderSet;
use geam::HostRegistrationError;
use geam::HostWorkProfile;

use geam::embedding::BigInt;
use geam::embedding::BindingError;
use geam::embedding::Function;
use geam::embedding::FunctionDeclaration;
use geam::embedding::HostedModuleBindings;
use geam::embedding::HostedModuleBuilder;
use geam::embedding::HostedProject;
use geam::embedding::InputShape;

pub const ROOT_MODULE: &str = "geam_global_value_embedding";

pub struct Profile;

pub type ProviderSet = HostProviderSet<Profile>;

#[derive(Default)]
pub struct Stores {
    future: <geam::FutureComponent as HostProviderComponent>::Stores,
    provider_global_value: <geam_global_value::Component as HostProviderComponent>::Stores,
}

pub struct RunStateInputs {
    pub global_value: HostProviderConfiguration,
}

impl RunStateInputs {
    pub fn initialize(self) -> Result<RunState, HostProviderInitializationError> {
        Ok(RunState {
            future: (),
            provider_global_value:
                <geam_global_value::Component as HostProviderComponentInitialization>::initialize(
                    &self.global_value,
                )?,
        })
    }
}

pub struct RunState {
    future: <geam::FutureComponent as HostProviderComponent>::RunState,
    provider_global_value: <geam_global_value::Component as HostProviderComponent>::RunState,
}

#[rustfmt::skip]
impl HostProfile for Profile {
    type ExternalStores = Stores;
    type RunState = RunState;
    type ExecutionState = geam::execution::ExecutionServices<<geam_global_value::Component as geam::HostExecutionService>::State, ()>;
    fn initialize_execution(state: &mut Self::RunState) -> Self::ExecutionState {
        geam::execution::ExecutionServices {
            first: <geam_global_value::Component as geam::HostExecutionService>::initialize_service(&mut state.provider_global_value),
            rest: (),
        }
    }
}

#[rustfmt::skip]
impl geam::HostServiceProfile<geam_global_value::Component> for Profile {
    fn service(state: &mut Self::ExecutionState) -> &mut <geam_global_value::Component as geam::HostExecutionService>::State {
        &mut state.first
    }
}

impl HostWorkProfile for Profile {
    type Work = geam::FutureComponent;
}

impl HostComponentProfile<geam::FutureComponent> for Profile {
    fn component_stores(
        stores: &Self::ExternalStores,
    ) -> &<geam::FutureComponent as HostProviderComponent>::Stores {
        &stores.future
    }

    fn component_state(
        state: &mut Self::RunState,
    ) -> &mut <geam::FutureComponent as HostProviderComponent>::RunState {
        &mut state.future
    }
}

impl HostComponentProfile<geam_global_value::Component> for Profile {
    fn component_stores(
        stores: &Self::ExternalStores,
    ) -> &<geam_global_value::Component as HostProviderComponent>::Stores {
        &stores.provider_global_value
    }

    fn component_state(
        state: &mut Self::RunState,
    ) -> &mut <geam_global_value::Component as HostProviderComponent>::RunState {
        &mut state.provider_global_value
    }
}

pub fn host_providers() -> Result<ProviderSet, HostRegistrationError> {
    let providers = <geam_global_value::Component as ComponentRegistration<Profile>>::providers()?;
    HostProviderSet::from_providers(providers)
}

pub fn project() -> HostedProject<Profile> {
    HostedProject::new(
        concat!(env!("CARGO_MANIFEST_DIR"), "/gleam"),
        ROOT_MODULE,
        host_providers,
    )
}

#[allow(clippy::type_complexity)]
pub struct Functions {
    pub first: Function<(BigInt,), BigInt, Function0Input>,
    pub second: Function<(), BigInt, Function1Input>,
    pub other: Function<(), BigInt, Function2Input>,
}

pub struct Function0Input;

impl InputShape<(BigInt,)> for Function0Input {}

pub struct Function1Input;

impl InputShape<()> for Function1Input {}

pub struct Function2Input;

impl InputShape<()> for Function2Input {}

pub fn bind(
    builder: HostedModuleBuilder<Profile>,
) -> Result<(HostedModuleBindings<Profile>, Functions), BindingError> {
    let (mut bindings, function_0) = builder.function(FunctionDeclaration::new("first"))?;
    let function_1 = bindings.function(FunctionDeclaration::new("second"))?;
    let function_2 = bindings.function(FunctionDeclaration::new("other"))?;
    Ok((
        bindings,
        Functions {
            first: function_0.with_input_shape(),
            second: function_1.with_input_shape(),
            other: function_2.with_input_shape(),
        },
    ))
}
