[workspace]
members = ["filepath", "gleam-regexp", "gleam-otp", "houdini", "gzlib", "gleam-crypto", "simplifile", "platform", "logging", "term-size", "birl", "gleam-httpc", "global-value", "argv", "splitter", "envoy", "operating-system"]
resolver = "3"

[workspace.package]
edition = "2024"
rust-version = "1.96"
license = "Apache-2.0"

[workspace.dependencies]
geam = { git = "https://github.com/panarch/geam.git", rev = "cf5fb100c9220d9e30ff60a11d5bfbeb77f1ebef", default-features = false, features = ["provider"] }
geam-core = { git = "https://github.com/panarch/geam.git", rev = "cf5fb100c9220d9e30ff60a11d5bfbeb77f1ebef" }
regex = "1.12"
regex-syntax = "0.8"
sha2 = "0.10"
sha1 = "0.10"
md-5 = "0.10"
getrandom = "0.4"
miniz_oxide = "0.9"
crc32fast = "1.5"
terminal_size = "=0.4.4"
jiff = "=0.2.37"
num-integer = "0.1"
reqwest = { version = "0.13.4", default-features = false, features = ["rustls"] }
memchr = "2.7"
