[workspace]
members = ["filepath", "gleam-regexp", "gleam-otp", "houdini", "gzlib", "simplifile"]
resolver = "3"

[workspace.package]
edition = "2024"
rust-version = "1.96"
license = "Apache-2.0"

[workspace.dependencies]
geam = { git = "https://github.com/panarch/geam.git", rev = "76c4ab7c6a2c0c35975bdd97e5de7c6284f895e7", default-features = false, features = ["provider"] }
geam-core = { git = "https://github.com/panarch/geam.git", rev = "76c4ab7c6a2c0c35975bdd97e5de7c6284f895e7" }
regex = "1.12"
regex-syntax = "0.8"
miniz_oxide = "0.9"
crc32fast = "1.5"
