// Generated by `geam embedding sync`. Do not edit.

use geam::HostComponentProfile;
use geam::HostProfile;
use geam::HostProviderComponent;
use geam::HostProviderComponentInitialization;
use geam::HostProviderComponentRegistration as ComponentRegistration;
use geam::HostProviderConfiguration;
use geam::HostProviderInitializationError;
use geam::HostProviderSet;
use geam::HostRegistrationError;
use geam::HostWorkProfile;

use geam::embedding::BindingError;
use geam::embedding::Function;
use geam::embedding::FunctionDeclaration;
use geam::embedding::HostedModule;
use geam::embedding::HostedModuleBindings;
use geam::embedding::HostedModuleBuilder;
use geam::embedding::HostedProject;
use geam::embedding::InputShape;
use geam::embedding::PreparedError;
use std::marker::PhantomData;

pub const ROOT_MODULE: &str = "geam_otp_embedding";

mod program;

pub struct Profile<Io>(PhantomData<fn() -> Io>);

pub type ProviderSet<Io> = HostProviderSet<Profile<Io>>;

pub struct Stores<Io>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    future: <geam::FutureComponent as HostProviderComponent>::Stores,
    stdlib: <geam::gleam_stdlib::Component<Io> as HostProviderComponent>::Stores,
    erlang: <geam::gleam_erlang::Component<Profile<Io>> as HostProviderComponent>::Stores,
    provider_gleam_otp: <geam_otp::Component<Profile<Io>> as HostProviderComponent>::Stores,
}

impl<Io> Default for Stores<Io>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    fn default() -> Self {
        Self {
            future: Default::default(),
            stdlib: Default::default(),
            erlang: Default::default(),
            provider_gleam_otp: Default::default(),
        }
    }
}

pub struct RunStateInputs<Io>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    pub stdlib: geam::gleam_stdlib::GleamStdlibRunState<Io>,
    pub erlang: geam::gleam_erlang::Configuration,
    pub gleam_otp: HostProviderConfiguration,
}

impl<Io> RunStateInputs<Io>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    pub fn initialize(self) -> Result<RunState<Io>, HostProviderInitializationError> {
        Ok(RunState {
            future: (),
            stdlib: self.stdlib,
            erlang: self.erlang,
            provider_gleam_otp:
                <geam_otp::Component<Profile<Io>> as HostProviderComponentInitialization>::initialize(
                    &self.gleam_otp,
                )?,
        })
    }
}

pub struct RunState<Io>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    future: <geam::FutureComponent as HostProviderComponent>::RunState,
    stdlib: <geam::gleam_stdlib::Component<Io> as HostProviderComponent>::RunState,
    erlang: <geam::gleam_erlang::Component<Profile<Io>> as HostProviderComponent>::RunState,
    provider_gleam_otp: <geam_otp::Component<Profile<Io>> as HostProviderComponent>::RunState,
}

impl<Io> RunState<Io>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    pub fn stdlib(&self) -> &geam::gleam_stdlib::GleamStdlibRunState<Io> {
        &self.stdlib
    }

    pub fn stdlib_mut(&mut self) -> &mut geam::gleam_stdlib::GleamStdlibRunState<Io> {
        &mut self.stdlib
    }
}

#[rustfmt::skip]
impl<Io> HostProfile for Profile<Io>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    type ExternalStores = Stores<Io>;
    type RunState = RunState<Io>;
    type ExecutionState = geam::execution::ExecutionServices<<geam::gleam_erlang::Component<Profile<Io>> as geam::HostExecutionService>::State, ()>;
    fn initialize_execution(state: &mut Self::RunState) -> Self::ExecutionState {
        geam::execution::ExecutionServices {
            first: <geam::gleam_erlang::Component<Profile<Io>> as geam::HostExecutionService>::initialize_service(&mut state.erlang),
            rest: (),
        }
    }
}

#[rustfmt::skip]
impl<Io> geam::HostServiceProfile<geam::gleam_erlang::Component<Profile<Io>>> for Profile<Io>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    fn service(state: &mut Self::ExecutionState) -> &mut <geam::gleam_erlang::Component<Profile<Io>> as geam::HostExecutionService>::State {
        &mut state.first
    }
}

impl<Io> HostWorkProfile for Profile<Io>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    type Work = geam::FutureComponent;
}

impl<Io> HostComponentProfile<geam::FutureComponent> for Profile<Io>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    fn component_stores(
        stores: &Self::ExternalStores,
    ) -> &<geam::FutureComponent as HostProviderComponent>::Stores {
        &stores.future
    }

    fn component_state(
        state: &mut Self::RunState,
    ) -> &mut <geam::FutureComponent as HostProviderComponent>::RunState {
        &mut state.future
    }
}

impl<Io> HostComponentProfile<geam::gleam_stdlib::Component<Io>> for Profile<Io>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    fn component_stores(
        stores: &Self::ExternalStores,
    ) -> &<geam::gleam_stdlib::Component<Io> as HostProviderComponent>::Stores {
        &stores.stdlib
    }

    fn component_state(
        state: &mut Self::RunState,
    ) -> &mut <geam::gleam_stdlib::Component<Io> as HostProviderComponent>::RunState {
        &mut state.stdlib
    }
}

impl<Io> HostComponentProfile<geam::gleam_erlang::Component<Profile<Io>>> for Profile<Io>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    fn component_stores(
        stores: &Self::ExternalStores,
    ) -> &<geam::gleam_erlang::Component<Profile<Io>> as HostProviderComponent>::Stores {
        &stores.erlang
    }

    fn component_state(
        state: &mut Self::RunState,
    ) -> &mut <geam::gleam_erlang::Component<Profile<Io>> as HostProviderComponent>::RunState {
        &mut state.erlang
    }
}

impl<Io> HostComponentProfile<geam_otp::Component<Profile<Io>>> for Profile<Io>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    fn component_stores(
        stores: &Self::ExternalStores,
    ) -> &<geam_otp::Component<Profile<Io>> as HostProviderComponent>::Stores {
        &stores.provider_gleam_otp
    }

    fn component_state(
        state: &mut Self::RunState,
    ) -> &mut <geam_otp::Component<Profile<Io>> as HostProviderComponent>::RunState {
        &mut state.provider_gleam_otp
    }
}

impl<Io> geam::gleam_stdlib::GleamStdlibHostProfile for Profile<Io>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    type Io = Io;
}

impl<Io> geam::gleam_erlang::GleamErlangHostProfile for Profile<Io>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    fn erlang_execution(
        state: &mut Self::ExecutionState,
    ) -> &mut geam::gleam_erlang::ErlangExecution {
        &mut state.first
    }
}

pub fn host_providers<Io>() -> Result<ProviderSet<Io>, HostRegistrationError>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    let mut providers =
        <geam::gleam_stdlib::Component<Io> as ComponentRegistration<Profile<Io>>>::providers()?;
    let additional_providers =
        <geam::gleam_erlang::Component<Profile<Io>> as ComponentRegistration<
            Profile<Io>,
        >>::providers()?;
    providers.extend(additional_providers);
    let additional_providers =
        <geam_otp::Component<Profile<Io>> as ComponentRegistration<Profile<Io>>>::providers()?;
    providers.extend(additional_providers);
    HostProviderSet::from_providers(providers)
}

#[allow(dead_code)]
pub fn project<Io>() -> HostedProject<Profile<Io>>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    HostedProject::new(
        concat!(env!("CARGO_MANIFEST_DIR"), "/gleam"),
        ROOT_MODULE,
        host_providers::<Io>,
    )
}

#[allow(clippy::type_complexity)]
pub struct Functions {
    pub main: Function<(), (), Function0Input>,
}

pub struct Function0Input;

impl InputShape<()> for Function0Input {}

#[allow(dead_code)]
pub fn bind<Io>(
    builder: HostedModuleBuilder<Profile<Io>>,
) -> Result<(HostedModuleBindings<Profile<Io>>, Functions), BindingError>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    let (bindings, function_0) = builder.function(FunctionDeclaration::new("main"))?;
    Ok((
        bindings,
        Functions {
            main: function_0.with_input_shape(),
        },
    ))
}

#[allow(dead_code)]
pub fn load<Io>() -> Result<(HostedModule<Profile<Io>>, Functions), PreparedError>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    let mut bindings = program::PROGRAM.load(host_providers::<Io>()?)?;
    let function_0 = bindings.function(FunctionDeclaration::new("main"))?;
    Ok((
        bindings.seal(),
        Functions {
            main: function_0.with_input_shape(),
        },
    ))
}
