[package]
name = "geam-regexp-embedding"
version = "0.1.0"
edition = "2024"
rust-version = "1.96"
publish = false

[dependencies]
geam = { git = "https://github.com/panarch/geam.git", rev = "bd95b872c578df88f76ed5c4175fb1ea55ee8607", default-features = false, features = ["embedding", "gleam-stdlib", "tokio", "geam-builtin"] }
geam-regexp = { path = "../.." }
tokio = { version = "1.53.1", default-features = false, features = ["rt"] }

[workspace]
resolver = "3"
