[package]
name = "geam-exception-embedding"
version = "0.1.0"
edition = "2024"
rust-version = "1.96"
publish = false

[dependencies]
geam = { git = "https://github.com/panarch/geam.git", rev = "5ad13b7a78652f95b6801e8bf836b9a1fb3ec789", default-features = false, features = ["embedding", "gleam-stdlib", "tokio", "geam-builtin"] }
geam-exception = { path = "../.." }
tokio = { version = "1.53.1", default-features = false, features = ["rt"] }

[workspace]
resolver = "3"
