// Generated by `geam embedding sync`. Do not edit.

use geam::HostComponentProfile;
use geam::HostProfile;
use geam::HostProviderComponent;
use geam::HostProviderComponentInitialization;
use geam::HostProviderComponentRegistration as ComponentRegistration;
use geam::HostProviderConfiguration;
use geam::HostProviderInitializationError;
use geam::HostProviderSet;
use geam::HostRegistrationError;
use geam::HostWorkProfile;

use geam::embedding::BindingError;
use geam::embedding::Function;
use geam::embedding::FunctionDeclaration;
use geam::embedding::HostedModuleBindings;
use geam::embedding::HostedModuleBuilder;
use geam::embedding::HostedProject;
use geam::embedding::InputShape;

pub const ROOT_MODULE: &str = "geam_logging_embedding";

pub struct Profile;

pub type ProviderSet = HostProviderSet<Profile>;

#[derive(Default)]
pub struct Stores {
    future: <geam::FutureComponent as HostProviderComponent>::Stores,
    provider_logging: <geam_logging::Component as HostProviderComponent>::Stores,
}

pub struct RunStateInputs {
    pub logging: HostProviderConfiguration,
}

impl RunStateInputs {
    pub fn initialize(self) -> Result<RunState, HostProviderInitializationError> {
        Ok(RunState {
            future: (),
            provider_logging:
                <geam_logging::Component as HostProviderComponentInitialization>::initialize(
                    &self.logging,
                )?,
        })
    }
}

pub struct RunState {
    future: <geam::FutureComponent as HostProviderComponent>::RunState,
    provider_logging: <geam_logging::Component as HostProviderComponent>::RunState,
}

impl HostProfile for Profile {
    type ExternalStores = Stores;
    type RunState = RunState;
    type ExecutionState = ();
}

impl HostWorkProfile for Profile {
    type Work = geam::FutureComponent;
}

impl HostComponentProfile<geam::FutureComponent> for Profile {
    fn component_stores(
        stores: &Self::ExternalStores,
    ) -> &<geam::FutureComponent as HostProviderComponent>::Stores {
        &stores.future
    }

    fn component_state(
        state: &mut Self::RunState,
    ) -> &mut <geam::FutureComponent as HostProviderComponent>::RunState {
        &mut state.future
    }
}

impl HostComponentProfile<geam_logging::Component> for Profile {
    fn component_stores(
        stores: &Self::ExternalStores,
    ) -> &<geam_logging::Component as HostProviderComponent>::Stores {
        &stores.provider_logging
    }

    fn component_state(
        state: &mut Self::RunState,
    ) -> &mut <geam_logging::Component as HostProviderComponent>::RunState {
        &mut state.provider_logging
    }
}

pub fn host_providers() -> Result<ProviderSet, HostRegistrationError> {
    let providers = <geam_logging::Component as ComponentRegistration<Profile>>::providers()?;
    HostProviderSet::from_providers(providers)
}

pub fn project() -> HostedProject<Profile> {
    HostedProject::new(
        concat!(env!("CARGO_MANIFEST_DIR"), "/gleam"),
        ROOT_MODULE,
        host_providers,
    )
}

#[allow(clippy::type_complexity)]
pub struct Functions {
    pub log_all_levels: Function<(), (), Function0Input>,
    pub filter_and_reset: Function<(), (), Function1Input>,
    pub log_one: Function<(), (), Function2Input>,
}

pub struct Function0Input;

impl InputShape<()> for Function0Input {}

pub struct Function1Input;

impl InputShape<()> for Function1Input {}

pub struct Function2Input;

impl InputShape<()> for Function2Input {}

pub fn bind(
    builder: HostedModuleBuilder<Profile>,
) -> Result<(HostedModuleBindings<Profile>, Functions), BindingError> {
    let (mut bindings, function_0) =
        builder.function(FunctionDeclaration::new("log_all_levels"))?;
    let function_1 = bindings.function(FunctionDeclaration::new("filter_and_reset"))?;
    let function_2 = bindings.function(FunctionDeclaration::new("log_one"))?;
    Ok((
        bindings,
        Functions {
            log_all_levels: function_0.with_input_shape(),
            filter_and_reset: function_1.with_input_shape(),
            log_one: function_2.with_input_shape(),
        },
    ))
}
