// Generated by `geam embedding sync`. Do not edit.

use geam::HostComponentProfile;
use geam::HostProfile;
use geam::HostProviderComponent;
use geam::HostProviderComponentInitialization;
use geam::HostProviderComponentRegistration as ComponentRegistration;
use geam::HostProviderConfiguration;
use geam::HostProviderInitializationError;
use geam::HostProviderSet;
use geam::HostRegistrationError;
use geam::HostWorkProfile;

use geam::embedding::BindingError;
use geam::embedding::Function;
use geam::embedding::FunctionDeclaration;
use geam::embedding::HostedModuleBindings;
use geam::embedding::HostedModuleBuilder;
use geam::embedding::HostedProject;
use geam::embedding::InputShape;
use geam::embedding::List;
use geam::embedding::StringValue;
use std::marker::PhantomData;

pub const ROOT_MODULE: &str = "geam_splitter_embedding";

pub struct Profile<Io>(PhantomData<fn() -> Io>);

pub type ProviderSet<Io> = HostProviderSet<Profile<Io>>;

pub struct Stores<Io>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    future: <geam::FutureComponent as HostProviderComponent>::Stores,
    stdlib: <geam::gleam_stdlib::Component<Io> as HostProviderComponent>::Stores,
    provider_splitter: <geam_splitter::Component as HostProviderComponent>::Stores,
}

impl<Io> Default for Stores<Io>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    fn default() -> Self {
        Self {
            future: Default::default(),
            stdlib: Default::default(),
            provider_splitter: Default::default(),
        }
    }
}

pub struct RunStateInputs<Io>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    pub stdlib: geam::gleam_stdlib::GleamStdlibRunState<Io>,
    pub splitter: HostProviderConfiguration,
}

impl<Io> RunStateInputs<Io>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    pub fn initialize(self) -> Result<RunState<Io>, HostProviderInitializationError> {
        Ok(RunState {
            future: (),
            stdlib: self.stdlib,
            provider_splitter:
                <geam_splitter::Component as HostProviderComponentInitialization>::initialize(
                    &self.splitter,
                )?,
        })
    }
}

pub struct RunState<Io>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    future: <geam::FutureComponent as HostProviderComponent>::RunState,
    stdlib: <geam::gleam_stdlib::Component<Io> as HostProviderComponent>::RunState,
    provider_splitter: <geam_splitter::Component as HostProviderComponent>::RunState,
}

impl<Io> RunState<Io>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    pub fn stdlib(&self) -> &geam::gleam_stdlib::GleamStdlibRunState<Io> {
        &self.stdlib
    }

    pub fn stdlib_mut(&mut self) -> &mut geam::gleam_stdlib::GleamStdlibRunState<Io> {
        &mut self.stdlib
    }
}

impl<Io> HostProfile for Profile<Io>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    type ExternalStores = Stores<Io>;
    type RunState = RunState<Io>;
    type ExecutionState = ();
}

impl<Io> HostWorkProfile for Profile<Io>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    type Work = geam::FutureComponent;
}

impl<Io> HostComponentProfile<geam::FutureComponent> for Profile<Io>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    fn component_stores(
        stores: &Self::ExternalStores,
    ) -> &<geam::FutureComponent as HostProviderComponent>::Stores {
        &stores.future
    }

    fn component_state(
        state: &mut Self::RunState,
    ) -> &mut <geam::FutureComponent as HostProviderComponent>::RunState {
        &mut state.future
    }
}

impl<Io> HostComponentProfile<geam::gleam_stdlib::Component<Io>> for Profile<Io>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    fn component_stores(
        stores: &Self::ExternalStores,
    ) -> &<geam::gleam_stdlib::Component<Io> as HostProviderComponent>::Stores {
        &stores.stdlib
    }

    fn component_state(
        state: &mut Self::RunState,
    ) -> &mut <geam::gleam_stdlib::Component<Io> as HostProviderComponent>::RunState {
        &mut state.stdlib
    }
}

impl<Io> HostComponentProfile<geam_splitter::Component> for Profile<Io>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    fn component_stores(
        stores: &Self::ExternalStores,
    ) -> &<geam_splitter::Component as HostProviderComponent>::Stores {
        &stores.provider_splitter
    }

    fn component_state(
        state: &mut Self::RunState,
    ) -> &mut <geam_splitter::Component as HostProviderComponent>::RunState {
        &mut state.provider_splitter
    }
}

impl<Io> geam::gleam_stdlib::GleamStdlibHostProfile for Profile<Io>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    type Io = Io;
}

pub fn host_providers<Io>() -> Result<ProviderSet<Io>, HostRegistrationError>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    let mut providers =
        <geam::gleam_stdlib::Component<Io> as ComponentRegistration<Profile<Io>>>::providers()?;
    let additional_providers =
        <geam_splitter::Component as ComponentRegistration<Profile<Io>>>::providers()?;
    providers.extend(additional_providers);
    HostProviderSet::from_providers(providers)
}

pub fn project<Io>() -> HostedProject<Profile<Io>>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    HostedProject::new(
        concat!(env!("CARGO_MANIFEST_DIR"), "/gleam"),
        ROOT_MODULE,
        host_providers::<Io>,
    )
}

#[allow(clippy::type_complexity)]
pub struct Functions {
    pub verify: Function<(), bool, Function0Input>,
    pub split_commas: Function<(StringValue,), List<StringValue>, Function1Input>,
}

pub struct Function0Input;

impl InputShape<()> for Function0Input {}

pub struct Function1Input;

impl InputShape<(StringValue,)> for Function1Input {}

pub fn bind<Io>(
    builder: HostedModuleBuilder<Profile<Io>>,
) -> Result<(HostedModuleBindings<Profile<Io>>, Functions), BindingError>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    let (mut bindings, function_0) = builder.function(FunctionDeclaration::new("verify"))?;
    let function_1 = bindings.function(FunctionDeclaration::new("split_commas"))?;
    Ok((
        bindings,
        Functions {
            verify: function_0.with_input_shape(),
            split_commas: function_1.with_input_shape(),
        },
    ))
}
