// Generated by `geam embedding sync`. Do not edit.

use geam::HostComponentProfile;
use geam::HostProfile;
use geam::HostProviderComponent;
use geam::HostProviderComponentInitialization;
use geam::HostProviderComponentRegistration as ComponentRegistration;
use geam::HostProviderConfiguration;
use geam::HostProviderInitializationError;
use geam::HostProviderSet;
use geam::HostRegistrationError;
use geam::HostWorkProfile;

use geam::embedding::BindingError;
use geam::embedding::BitArrayValue;
use geam::embedding::Function;
use geam::embedding::FunctionDeclaration;
use geam::embedding::HostedModule;
use geam::embedding::HostedModuleBindings;
use geam::embedding::HostedModuleBuilder;
use geam::embedding::HostedProject;
use geam::embedding::InputShape;
use geam::embedding::List;
use geam::embedding::PreparedError;
use geam::embedding::StringValue;
use std::marker::PhantomData;

pub const ROOT_MODULE: &str = "geam_gramps_embedding";

mod program;

pub struct Profile<Io>(PhantomData<fn() -> Io>);

pub type ProviderSet<Io> = HostProviderSet<Profile<Io>>;

pub struct Stores<Io>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    future: <geam::FutureComponent as HostProviderComponent>::Stores,
    stdlib: <geam::gleam_stdlib::Component<Io> as HostProviderComponent>::Stores,
    erlang: <geam::gleam_erlang::Component<Profile<Io>> as HostProviderComponent>::Stores,
    provider_gleam_crypto: <geam_crypto::Component as HostProviderComponent>::Stores,
    provider_gramps: <geam_gramps::Component as HostProviderComponent>::Stores,
}

impl<Io> Default for Stores<Io>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    fn default() -> Self {
        Self {
            future: Default::default(),
            stdlib: Default::default(),
            erlang: Default::default(),
            provider_gleam_crypto: Default::default(),
            provider_gramps: Default::default(),
        }
    }
}

pub struct RunStateInputs<Io>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    pub stdlib: geam::gleam_stdlib::GleamStdlibRunState<Io>,
    pub erlang: geam::gleam_erlang::Configuration,
    pub gleam_crypto: HostProviderConfiguration,
    pub gramps: HostProviderConfiguration,
}

impl<Io> RunStateInputs<Io>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    pub fn initialize(self) -> Result<RunState<Io>, HostProviderInitializationError> {
        Ok(RunState {
            future: (),
            stdlib: self.stdlib,
            erlang: self.erlang,
            provider_gleam_crypto:
                <geam_crypto::Component as HostProviderComponentInitialization>::initialize(
                    &self.gleam_crypto,
                )?,
            provider_gramps:
                <geam_gramps::Component as HostProviderComponentInitialization>::initialize(
                    &self.gramps,
                )?,
        })
    }
}

pub struct RunState<Io>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    future: <geam::FutureComponent as HostProviderComponent>::RunState,
    stdlib: <geam::gleam_stdlib::Component<Io> as HostProviderComponent>::RunState,
    erlang: <geam::gleam_erlang::Component<Profile<Io>> as HostProviderComponent>::RunState,
    provider_gleam_crypto: <geam_crypto::Component as HostProviderComponent>::RunState,
    provider_gramps: <geam_gramps::Component as HostProviderComponent>::RunState,
}

impl<Io> RunState<Io>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    pub fn stdlib(&self) -> &geam::gleam_stdlib::GleamStdlibRunState<Io> {
        &self.stdlib
    }

    pub fn stdlib_mut(&mut self) -> &mut geam::gleam_stdlib::GleamStdlibRunState<Io> {
        &mut self.stdlib
    }
}

#[rustfmt::skip]
impl<Io> HostProfile for Profile<Io>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    type ExternalStores = Stores<Io>;
    type RunState = RunState<Io>;
    type ExecutionState = geam::execution::ExecutionServices<<geam::gleam_erlang::Component<Profile<Io>> as geam::HostExecutionService>::State, geam::execution::ExecutionServices<<geam_gramps::Component as geam::HostExecutionService>::State, ()>>;
    fn initialize_execution(state: &mut Self::RunState) -> Self::ExecutionState {
        geam::execution::ExecutionServices {
            first: <geam::gleam_erlang::Component<Profile<Io>> as geam::HostExecutionService>::initialize_service(&mut state.erlang),
            rest: geam::execution::ExecutionServices {
                first: <geam_gramps::Component as geam::HostExecutionService>::initialize_service(&mut state.provider_gramps),
                rest: (),
            },
        }
    }
}

#[rustfmt::skip]
impl<Io> geam::HostServiceProfile<geam::gleam_erlang::Component<Profile<Io>>> for Profile<Io>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    fn service(state: &mut Self::ExecutionState) -> &mut <geam::gleam_erlang::Component<Profile<Io>> as geam::HostExecutionService>::State {
        &mut state.first
    }
}

#[rustfmt::skip]
impl<Io> geam::HostServiceProfile<geam_gramps::Component> for Profile<Io>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    fn service(state: &mut Self::ExecutionState) -> &mut <geam_gramps::Component as geam::HostExecutionService>::State {
        &mut state.rest.first
    }
}

impl<Io> HostWorkProfile for Profile<Io>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    type Work = geam::FutureComponent;
}

impl<Io> HostComponentProfile<geam::FutureComponent> for Profile<Io>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    fn component_stores(
        stores: &Self::ExternalStores,
    ) -> &<geam::FutureComponent as HostProviderComponent>::Stores {
        &stores.future
    }

    fn component_state(
        state: &mut Self::RunState,
    ) -> &mut <geam::FutureComponent as HostProviderComponent>::RunState {
        &mut state.future
    }
}

impl<Io> HostComponentProfile<geam::gleam_stdlib::Component<Io>> for Profile<Io>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    fn component_stores(
        stores: &Self::ExternalStores,
    ) -> &<geam::gleam_stdlib::Component<Io> as HostProviderComponent>::Stores {
        &stores.stdlib
    }

    fn component_state(
        state: &mut Self::RunState,
    ) -> &mut <geam::gleam_stdlib::Component<Io> as HostProviderComponent>::RunState {
        &mut state.stdlib
    }
}

impl<Io> HostComponentProfile<geam::gleam_erlang::Component<Profile<Io>>> for Profile<Io>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    fn component_stores(
        stores: &Self::ExternalStores,
    ) -> &<geam::gleam_erlang::Component<Profile<Io>> as HostProviderComponent>::Stores {
        &stores.erlang
    }

    fn component_state(
        state: &mut Self::RunState,
    ) -> &mut <geam::gleam_erlang::Component<Profile<Io>> as HostProviderComponent>::RunState {
        &mut state.erlang
    }
}

impl<Io> HostComponentProfile<geam_crypto::Component> for Profile<Io>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    fn component_stores(
        stores: &Self::ExternalStores,
    ) -> &<geam_crypto::Component as HostProviderComponent>::Stores {
        &stores.provider_gleam_crypto
    }

    fn component_state(
        state: &mut Self::RunState,
    ) -> &mut <geam_crypto::Component as HostProviderComponent>::RunState {
        &mut state.provider_gleam_crypto
    }
}

impl<Io> HostComponentProfile<geam_gramps::Component> for Profile<Io>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    fn component_stores(
        stores: &Self::ExternalStores,
    ) -> &<geam_gramps::Component as HostProviderComponent>::Stores {
        &stores.provider_gramps
    }

    fn component_state(
        state: &mut Self::RunState,
    ) -> &mut <geam_gramps::Component as HostProviderComponent>::RunState {
        &mut state.provider_gramps
    }
}

impl<Io> geam::gleam_stdlib::GleamStdlibHostProfile for Profile<Io>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    type Io = Io;
}

impl<Io> geam::gleam_erlang::GleamErlangHostProfile for Profile<Io>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    fn erlang_execution(
        state: &mut Self::ExecutionState,
    ) -> &mut geam::gleam_erlang::ErlangExecution {
        &mut state.first
    }
}

pub fn host_providers<Io>() -> Result<ProviderSet<Io>, HostRegistrationError>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    let mut providers =
        <geam::gleam_stdlib::Component<Io> as ComponentRegistration<Profile<Io>>>::providers()?;
    let additional_providers =
        <geam::gleam_erlang::Component<Profile<Io>> as ComponentRegistration<
            Profile<Io>,
        >>::providers()?;
    providers.extend(additional_providers);
    let additional_providers =
        <geam_crypto::Component as ComponentRegistration<Profile<Io>>>::providers()?;
    providers.extend(additional_providers);
    let additional_providers =
        <geam_gramps::Component as ComponentRegistration<Profile<Io>>>::providers()?;
    providers.extend(additional_providers);
    HostProviderSet::from_providers(providers)
}

#[allow(dead_code)]
pub fn project<Io>() -> HostedProject<Profile<Io>>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    HostedProject::new(
        concat!(env!("CARGO_MANIFEST_DIR"), "/gleam"),
        ROOT_MODULE,
        host_providers::<Io>,
    )
}

#[allow(clippy::type_complexity)]
pub struct Functions {
    pub verify: Function<(), bool, Function0Input>,
    pub round_trip: Function<(StringValue,), BitArrayValue, Function1Input>,
    pub closed: Function<(), BitArrayValue, Function2Input>,
    pub malformed: Function<(), BitArrayValue, Function3Input>,
    pub partial: Function<(), BitArrayValue, Function4Input>,
    pub client_key: Function<(), StringValue, Function5Input>,
    pub compress: Function<(List<BitArrayValue>, bool), List<BitArrayValue>, Function6Input>,
    pub decompress: Function<(List<BitArrayValue>, bool), List<BitArrayValue>, Function7Input>,
}

pub struct Function0Input;

impl InputShape<()> for Function0Input {}

pub struct Function1Input;

impl InputShape<(StringValue,)> for Function1Input {}

pub struct Function2Input;

impl InputShape<()> for Function2Input {}

pub struct Function3Input;

impl InputShape<()> for Function3Input {}

pub struct Function4Input;

impl InputShape<()> for Function4Input {}

pub struct Function5Input;

impl InputShape<()> for Function5Input {}

pub struct Function6Input;

impl<Input0> InputShape<(Input0, bool)> for Function6Input {}

pub struct Function7Input;

impl<Input0> InputShape<(Input0, bool)> for Function7Input {}

#[allow(dead_code)]
pub fn bind<Io>(
    builder: HostedModuleBuilder<Profile<Io>>,
) -> Result<(HostedModuleBindings<Profile<Io>>, Functions), BindingError>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    let (mut bindings, function_0) = builder.function(FunctionDeclaration::new("verify"))?;
    let function_1 = bindings.function(FunctionDeclaration::new("round_trip"))?;
    let function_2 = bindings.function(FunctionDeclaration::new("closed"))?;
    let function_3 = bindings.function(FunctionDeclaration::new("malformed"))?;
    let function_4 = bindings.function(FunctionDeclaration::new("partial"))?;
    let function_5 = bindings.function(FunctionDeclaration::new("client_key"))?;
    let function_6 = bindings.function(FunctionDeclaration::new("compress"))?;
    let function_7 = bindings.function(FunctionDeclaration::new("decompress"))?;
    Ok((
        bindings,
        Functions {
            verify: function_0.with_input_shape(),
            round_trip: function_1.with_input_shape(),
            closed: function_2.with_input_shape(),
            malformed: function_3.with_input_shape(),
            partial: function_4.with_input_shape(),
            client_key: function_5.with_input_shape(),
            compress: function_6.with_input_shape(),
            decompress: function_7.with_input_shape(),
        },
    ))
}

#[allow(dead_code)]
pub fn load<Io>() -> Result<(HostedModule<Profile<Io>>, Functions), PreparedError>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    let mut bindings = program::PROGRAM.load(host_providers::<Io>()?)?;
    let function_0 = bindings.function(FunctionDeclaration::new("verify"))?;
    let function_1 = bindings.function(FunctionDeclaration::new("round_trip"))?;
    let function_2 = bindings.function(FunctionDeclaration::new("closed"))?;
    let function_3 = bindings.function(FunctionDeclaration::new("malformed"))?;
    let function_4 = bindings.function(FunctionDeclaration::new("partial"))?;
    let function_5 = bindings.function(FunctionDeclaration::new("client_key"))?;
    let function_6 = bindings.function(FunctionDeclaration::new("compress"))?;
    let function_7 = bindings.function(FunctionDeclaration::new("decompress"))?;
    Ok((
        bindings.seal(),
        Functions {
            verify: function_0.with_input_shape(),
            round_trip: function_1.with_input_shape(),
            closed: function_2.with_input_shape(),
            malformed: function_3.with_input_shape(),
            partial: function_4.with_input_shape(),
            client_key: function_5.with_input_shape(),
            compress: function_6.with_input_shape(),
            decompress: function_7.with_input_shape(),
        },
    ))
}
