// Generated by `geam embedding sync`. Do not edit.

use geam::HostComponentProfile;
use geam::HostProfile;
use geam::HostProviderComponent;
use geam::HostProviderComponentInitialization;
use geam::HostProviderComponentRegistration as ComponentRegistration;
use geam::HostProviderConfiguration;
use geam::HostProviderInitializationError;
use geam::HostProviderSet;
use geam::HostRegistrationError;
use geam::HostWorkProfile;

use geam::embedding::BindingError;
use geam::embedding::Function;
use geam::embedding::FunctionDeclaration;
use geam::embedding::HostedModule;
use geam::embedding::HostedModuleBindings;
use geam::embedding::HostedModuleBuilder;
use geam::embedding::HostedProject;
use geam::embedding::InputShape;
use geam::embedding::PreparedError;
use geam::embedding::StringValue;
use std::marker::PhantomData;

pub const ROOT_MODULE: &str = "geam_httpc_embedding";

mod program;

pub struct Profile<Io>(PhantomData<fn() -> Io>);

pub type ProviderSet<Io> = HostProviderSet<Profile<Io>>;

pub struct Stores<Io>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    future: <geam::FutureComponent as HostProviderComponent>::Stores,
    stdlib: <geam::gleam_stdlib::Component<Io> as HostProviderComponent>::Stores,
    erlang: <geam::gleam_erlang::Component<Profile<Io>> as HostProviderComponent>::Stores,
    provider_gleam_httpc: <geam_httpc::Component<Profile<Io>> as HostProviderComponent>::Stores,
}

impl<Io> Default for Stores<Io>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    fn default() -> Self {
        Self {
            future: Default::default(),
            stdlib: Default::default(),
            erlang: Default::default(),
            provider_gleam_httpc: Default::default(),
        }
    }
}

pub struct RunStateInputs<Io>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    pub stdlib: geam::gleam_stdlib::GleamStdlibRunState<Io>,
    pub erlang: geam::gleam_erlang::Configuration,
    pub gleam_httpc: HostProviderConfiguration,
}

impl<Io> RunStateInputs<Io>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    pub fn initialize(self) -> Result<RunState<Io>, HostProviderInitializationError> {
        Ok(RunState {
            future: (),
            stdlib: self.stdlib,
            erlang: self.erlang,
            provider_gleam_httpc:
                <geam_httpc::Component<Profile<Io>> as HostProviderComponentInitialization>::initialize(
                    &self.gleam_httpc,
                )?,
        })
    }
}

pub struct RunState<Io>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    future: <geam::FutureComponent as HostProviderComponent>::RunState,
    stdlib: <geam::gleam_stdlib::Component<Io> as HostProviderComponent>::RunState,
    erlang: <geam::gleam_erlang::Component<Profile<Io>> as HostProviderComponent>::RunState,
    provider_gleam_httpc: <geam_httpc::Component<Profile<Io>> as HostProviderComponent>::RunState,
}

impl<Io> RunState<Io>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    pub fn stdlib(&self) -> &geam::gleam_stdlib::GleamStdlibRunState<Io> {
        &self.stdlib
    }

    pub fn stdlib_mut(&mut self) -> &mut geam::gleam_stdlib::GleamStdlibRunState<Io> {
        &mut self.stdlib
    }
}

#[rustfmt::skip]
impl<Io> HostProfile for Profile<Io>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    type ExternalStores = Stores<Io>;
    type RunState = RunState<Io>;
    type ExecutionState = geam::execution::ExecutionServices<<geam::gleam_erlang::Component<Profile<Io>> as geam::HostExecutionService>::State, ()>;
    fn initialize_execution(state: &mut Self::RunState) -> Self::ExecutionState {
        geam::execution::ExecutionServices {
            first: <geam::gleam_erlang::Component<Profile<Io>> as geam::HostExecutionService>::initialize_service(&mut state.erlang),
            rest: (),
        }
    }
}

#[rustfmt::skip]
impl<Io> geam::HostServiceProfile<geam::gleam_erlang::Component<Profile<Io>>> for Profile<Io>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    fn service(state: &mut Self::ExecutionState) -> &mut <geam::gleam_erlang::Component<Profile<Io>> as geam::HostExecutionService>::State {
        &mut state.first
    }
}

impl<Io> HostWorkProfile for Profile<Io>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    type Work = geam::FutureComponent;
}

impl<Io> HostComponentProfile<geam::FutureComponent> for Profile<Io>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    fn component_stores(
        stores: &Self::ExternalStores,
    ) -> &<geam::FutureComponent as HostProviderComponent>::Stores {
        &stores.future
    }

    fn component_state(
        state: &mut Self::RunState,
    ) -> &mut <geam::FutureComponent as HostProviderComponent>::RunState {
        &mut state.future
    }
}

impl<Io> HostComponentProfile<geam::gleam_stdlib::Component<Io>> for Profile<Io>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    fn component_stores(
        stores: &Self::ExternalStores,
    ) -> &<geam::gleam_stdlib::Component<Io> as HostProviderComponent>::Stores {
        &stores.stdlib
    }

    fn component_state(
        state: &mut Self::RunState,
    ) -> &mut <geam::gleam_stdlib::Component<Io> as HostProviderComponent>::RunState {
        &mut state.stdlib
    }
}

impl<Io> HostComponentProfile<geam::gleam_erlang::Component<Profile<Io>>> for Profile<Io>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    fn component_stores(
        stores: &Self::ExternalStores,
    ) -> &<geam::gleam_erlang::Component<Profile<Io>> as HostProviderComponent>::Stores {
        &stores.erlang
    }

    fn component_state(
        state: &mut Self::RunState,
    ) -> &mut <geam::gleam_erlang::Component<Profile<Io>> as HostProviderComponent>::RunState {
        &mut state.erlang
    }
}

impl<Io> HostComponentProfile<geam_httpc::Component<Profile<Io>>> for Profile<Io>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    fn component_stores(
        stores: &Self::ExternalStores,
    ) -> &<geam_httpc::Component<Profile<Io>> as HostProviderComponent>::Stores {
        &stores.provider_gleam_httpc
    }

    fn component_state(
        state: &mut Self::RunState,
    ) -> &mut <geam_httpc::Component<Profile<Io>> as HostProviderComponent>::RunState {
        &mut state.provider_gleam_httpc
    }
}

impl<Io> geam::gleam_stdlib::GleamStdlibHostProfile for Profile<Io>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    type Io = Io;
}

impl<Io> geam::gleam_erlang::GleamErlangHostProfile for Profile<Io>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    fn erlang_execution(
        state: &mut Self::ExecutionState,
    ) -> &mut geam::gleam_erlang::ErlangExecution {
        &mut state.first
    }
}

pub fn host_providers<Io>() -> Result<ProviderSet<Io>, HostRegistrationError>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    let mut providers =
        <geam::gleam_stdlib::Component<Io> as ComponentRegistration<Profile<Io>>>::providers()?;
    let additional_providers =
        <geam::gleam_erlang::Component<Profile<Io>> as ComponentRegistration<
            Profile<Io>,
        >>::providers()?;
    providers.extend(additional_providers);
    let additional_providers =
        <geam_httpc::Component<Profile<Io>> as ComponentRegistration<Profile<Io>>>::providers()?;
    providers.extend(additional_providers);
    HostProviderSet::from_providers(providers)
}

#[allow(dead_code)]
pub fn project<Io>() -> HostedProject<Profile<Io>>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    HostedProject::new(
        concat!(env!("CARGO_MANIFEST_DIR"), "/gleam"),
        ROOT_MODULE,
        host_providers::<Io>,
    )
}

#[allow(clippy::type_complexity)]
pub struct Functions {
    pub verify: Function<(StringValue,), bool, Function0Input>,
    pub methods: Function<(StringValue,), bool, Function1Input>,
    pub options_and_headers: Function<(StringValue,), bool, Function2Input>,
    pub binary_response: Function<(StringValue,), bool, Function3Input>,
    pub invalid_utf8: Function<(StringValue,), bool, Function4Input>,
    pub timeout: Function<(StringValue,), bool, Function5Input>,
    pub posix_error: Function<(StringValue,), bool, Function6Input>,
    pub tls_error: Function<(StringValue,), bool, Function7Input>,
    pub negative_timeout: Function<(StringValue,), bool, Function8Input>,
    pub negative_timeout_body: Function<(StringValue,), bool, Function9Input>,
    pub unaligned_request: Function<(StringValue,), bool, Function10Input>,
    pub invalid_method: Function<(StringValue,), bool, Function11Input>,
}

pub struct Function0Input;

impl InputShape<(StringValue,)> for Function0Input {}

pub struct Function1Input;

impl InputShape<(StringValue,)> for Function1Input {}

pub struct Function2Input;

impl InputShape<(StringValue,)> for Function2Input {}

pub struct Function3Input;

impl InputShape<(StringValue,)> for Function3Input {}

pub struct Function4Input;

impl InputShape<(StringValue,)> for Function4Input {}

pub struct Function5Input;

impl InputShape<(StringValue,)> for Function5Input {}

pub struct Function6Input;

impl InputShape<(StringValue,)> for Function6Input {}

pub struct Function7Input;

impl InputShape<(StringValue,)> for Function7Input {}

pub struct Function8Input;

impl InputShape<(StringValue,)> for Function8Input {}

pub struct Function9Input;

impl InputShape<(StringValue,)> for Function9Input {}

pub struct Function10Input;

impl InputShape<(StringValue,)> for Function10Input {}

pub struct Function11Input;

impl InputShape<(StringValue,)> for Function11Input {}

#[allow(dead_code)]
pub fn bind<Io>(
    builder: HostedModuleBuilder<Profile<Io>>,
) -> Result<(HostedModuleBindings<Profile<Io>>, Functions), BindingError>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    let (mut bindings, function_0) = builder.function(FunctionDeclaration::new("verify"))?;
    let function_1 = bindings.function(FunctionDeclaration::new("methods"))?;
    let function_2 = bindings.function(FunctionDeclaration::new("options_and_headers"))?;
    let function_3 = bindings.function(FunctionDeclaration::new("binary_response"))?;
    let function_4 = bindings.function(FunctionDeclaration::new("invalid_utf8"))?;
    let function_5 = bindings.function(FunctionDeclaration::new("timeout"))?;
    let function_6 = bindings.function(FunctionDeclaration::new("posix_error"))?;
    let function_7 = bindings.function(FunctionDeclaration::new("tls_error"))?;
    let function_8 = bindings.function(FunctionDeclaration::new("negative_timeout"))?;
    let function_9 = bindings.function(FunctionDeclaration::new("negative_timeout_body"))?;
    let function_10 = bindings.function(FunctionDeclaration::new("unaligned_request"))?;
    let function_11 = bindings.function(FunctionDeclaration::new("invalid_method"))?;
    Ok((
        bindings,
        Functions {
            verify: function_0.with_input_shape(),
            methods: function_1.with_input_shape(),
            options_and_headers: function_2.with_input_shape(),
            binary_response: function_3.with_input_shape(),
            invalid_utf8: function_4.with_input_shape(),
            timeout: function_5.with_input_shape(),
            posix_error: function_6.with_input_shape(),
            tls_error: function_7.with_input_shape(),
            negative_timeout: function_8.with_input_shape(),
            negative_timeout_body: function_9.with_input_shape(),
            unaligned_request: function_10.with_input_shape(),
            invalid_method: function_11.with_input_shape(),
        },
    ))
}

#[allow(dead_code)]
pub fn load<Io>() -> Result<(HostedModule<Profile<Io>>, Functions), PreparedError>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    let mut bindings = program::PROGRAM.load(host_providers::<Io>()?)?;
    let function_0 = bindings.function(FunctionDeclaration::new("verify"))?;
    let function_1 = bindings.function(FunctionDeclaration::new("methods"))?;
    let function_2 = bindings.function(FunctionDeclaration::new("options_and_headers"))?;
    let function_3 = bindings.function(FunctionDeclaration::new("binary_response"))?;
    let function_4 = bindings.function(FunctionDeclaration::new("invalid_utf8"))?;
    let function_5 = bindings.function(FunctionDeclaration::new("timeout"))?;
    let function_6 = bindings.function(FunctionDeclaration::new("posix_error"))?;
    let function_7 = bindings.function(FunctionDeclaration::new("tls_error"))?;
    let function_8 = bindings.function(FunctionDeclaration::new("negative_timeout"))?;
    let function_9 = bindings.function(FunctionDeclaration::new("negative_timeout_body"))?;
    let function_10 = bindings.function(FunctionDeclaration::new("unaligned_request"))?;
    let function_11 = bindings.function(FunctionDeclaration::new("invalid_method"))?;
    Ok((
        bindings.seal(),
        Functions {
            verify: function_0.with_input_shape(),
            methods: function_1.with_input_shape(),
            options_and_headers: function_2.with_input_shape(),
            binary_response: function_3.with_input_shape(),
            invalid_utf8: function_4.with_input_shape(),
            timeout: function_5.with_input_shape(),
            posix_error: function_6.with_input_shape(),
            tls_error: function_7.with_input_shape(),
            negative_timeout: function_8.with_input_shape(),
            negative_timeout_body: function_9.with_input_shape(),
            unaligned_request: function_10.with_input_shape(),
            invalid_method: function_11.with_input_shape(),
        },
    ))
}
