// Generated by `geam embedding sync`. Do not edit.

use geam::HostComponentProfile;
use geam::HostProfile;
use geam::HostProviderComponent;
use geam::HostProviderComponentInitialization;
use geam::HostProviderComponentRegistration as ComponentRegistration;
use geam::HostProviderConfiguration;
use geam::HostProviderInitializationError;
use geam::HostProviderSet;
use geam::HostRegistrationError;
use geam::HostWorkProfile;

use geam::embedding::BindingError;
use geam::embedding::Function;
use geam::embedding::FunctionDeclaration;
use geam::embedding::HostedModuleBindings;
use geam::embedding::HostedModuleBuilder;
use geam::embedding::HostedProject;
use geam::embedding::InputShape;
use geam::embedding::StringValue;

pub const ROOT_MODULE: &str = "geam_operating_system_embedding";

pub struct Profile;

pub type ProviderSet = HostProviderSet<Profile>;

#[derive(Default)]
pub struct Stores {
    future: <geam::FutureComponent as HostProviderComponent>::Stores,
    provider_operating_system: <geam_operating_system::Component as HostProviderComponent>::Stores,
}

pub struct RunStateInputs {
    pub operating_system: HostProviderConfiguration,
}

impl RunStateInputs {
    pub fn initialize(self) -> Result<RunState, HostProviderInitializationError> {
        Ok(RunState {
            future: (),
            provider_operating_system:
                <geam_operating_system::Component as HostProviderComponentInitialization>::initialize(
                    &self.operating_system,
                )?,
        })
    }
}

pub struct RunState {
    future: <geam::FutureComponent as HostProviderComponent>::RunState,
    provider_operating_system:
        <geam_operating_system::Component as HostProviderComponent>::RunState,
}

impl HostProfile for Profile {
    type ExternalStores = Stores;
    type RunState = RunState;
    type ExecutionState = ();
}

impl HostWorkProfile for Profile {
    type Work = geam::FutureComponent;
}

impl HostComponentProfile<geam::FutureComponent> for Profile {
    fn component_stores(
        stores: &Self::ExternalStores,
    ) -> &<geam::FutureComponent as HostProviderComponent>::Stores {
        &stores.future
    }

    fn component_state(
        state: &mut Self::RunState,
    ) -> &mut <geam::FutureComponent as HostProviderComponent>::RunState {
        &mut state.future
    }
}

impl HostComponentProfile<geam_operating_system::Component> for Profile {
    fn component_stores(
        stores: &Self::ExternalStores,
    ) -> &<geam_operating_system::Component as HostProviderComponent>::Stores {
        &stores.provider_operating_system
    }

    fn component_state(
        state: &mut Self::RunState,
    ) -> &mut <geam_operating_system::Component as HostProviderComponent>::RunState {
        &mut state.provider_operating_system
    }
}

pub fn host_providers() -> Result<ProviderSet, HostRegistrationError> {
    let providers =
        <geam_operating_system::Component as ComponentRegistration<Profile>>::providers()?;
    HostProviderSet::from_providers(providers)
}

pub fn project() -> HostedProject<Profile> {
    HostedProject::new(
        concat!(env!("CARGO_MANIFEST_DIR"), "/gleam"),
        ROOT_MODULE,
        host_providers,
    )
}

#[allow(clippy::type_complexity)]
pub struct Functions {
    pub name: Function<(), StringValue, Function0Input>,
}

pub struct Function0Input;

impl InputShape<()> for Function0Input {}

pub fn bind(
    builder: HostedModuleBuilder<Profile>,
) -> Result<(HostedModuleBindings<Profile>, Functions), BindingError> {
    let (bindings, function_0) = builder.function(FunctionDeclaration::new("name"))?;
    Ok((
        bindings,
        Functions {
            name: function_0.with_input_shape(),
        },
    ))
}
