[package]
name = "geam-clip-cli-native"
version = "0.1.0"
edition = "2024"
rust-version = "1.96"
publish = false

[package.metadata.geam.provider]
schema = 1
gleam-package = "geam_clip_search"
gleam-version = ">= 0.1.0 and < 0.2.0"

[dependencies]
geam = { git = "https://github.com/panarch/geam.git", rev = "08b5651661f83d59423ff20e271c62fb42a2f2ae", default-features = false, features = ["provider"] }

[workspace]
resolver = "3"
