[package]
name = "geam-birl-embedding"
version = "0.1.0"
edition = "2024"
rust-version = "1.96"
publish = false

[dependencies]
geam = { git = "https://github.com/panarch/geam.git", rev = "08b5651661f83d59423ff20e271c62fb42a2f2ae", default-features = false, features = ["embedding", "gleam-stdlib", "gleam-time", "tokio", "geam-builtin"] }
geam-birl = { path = "../.." }
geam-regexp = { path = "../../../gleam-regexp" }
tokio = { version = "1.53.1", default-features = false, features = ["rt"] }

[workspace]
resolver = "3"
