// Generated by `geam embedding sync`. Do not edit.

use geam::HostComponentProfile;
use geam::HostProfile;
use geam::HostProviderComponent;
use geam::HostProviderComponentInitialization;
use geam::HostProviderComponentRegistration as ComponentRegistration;
use geam::HostProviderConfiguration;
use geam::HostProviderInitializationError;
use geam::HostProviderSet;
use geam::HostRegistrationError;
use geam::HostWorkProfile;

use geam::embedding::BindingError;
use geam::embedding::Function;
use geam::embedding::FunctionDeclaration;
use geam::embedding::HostedModuleBindings;
use geam::embedding::HostedModuleBuilder;
use geam::embedding::HostedProject;
use geam::embedding::InputShape;
use geam::embedding::List;
use geam::embedding::StringValue;
use std::marker::PhantomData;

pub const ROOT_MODULE: &str = "geam_clip_embedding";

/// Opaque `geam_clip_search:geam_clip_search.Outcome` in this execution domain.
pub type Type0 = geam::embedding::CustomType<Type0Schema>;

pub struct Type0Schema;

impl geam::embedding::NamedTypeSchema for Type0Schema {
    const PACKAGE: &'static str = "geam_clip_search";
    const MODULE: &'static str = "geam_clip_search";
    const NAME: &'static str = "Outcome";
}

pub struct Profile<Io>(PhantomData<fn() -> Io>);

pub type ProviderSet<Io> = HostProviderSet<Profile<Io>>;

pub struct Stores<Io>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    future: <geam::FutureComponent as HostProviderComponent>::Stores,
    stdlib: <geam::gleam_stdlib::Component<Io> as HostProviderComponent>::Stores,
    provider_argv: <geam_argv::Component as HostProviderComponent>::Stores,
    provider_filepath: <geam_filepath::Component as HostProviderComponent>::Stores,
    provider_geam_clip_search: <geam_clip_cli_native::Component as HostProviderComponent>::Stores,
    provider_gleam_regexp: <geam_regexp::Component as HostProviderComponent>::Stores,
    provider_simplifile: <geam_simplifile::Component as HostProviderComponent>::Stores,
}

impl<Io> Default for Stores<Io>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    fn default() -> Self {
        Self {
            future: Default::default(),
            stdlib: Default::default(),
            provider_argv: Default::default(),
            provider_filepath: Default::default(),
            provider_geam_clip_search: Default::default(),
            provider_gleam_regexp: Default::default(),
            provider_simplifile: Default::default(),
        }
    }
}

pub struct RunStateInputs<Io>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    pub stdlib: geam::gleam_stdlib::GleamStdlibRunState<Io>,
    pub argv: HostProviderConfiguration,
    pub filepath: HostProviderConfiguration,
    pub geam_clip_search: HostProviderConfiguration,
    pub gleam_regexp: HostProviderConfiguration,
    pub simplifile: HostProviderConfiguration,
}

impl<Io> RunStateInputs<Io>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    pub fn initialize(self) -> Result<RunState<Io>, HostProviderInitializationError> {
        Ok(RunState {
            future: (),
            stdlib: self.stdlib,
            provider_argv:
                <geam_argv::Component as HostProviderComponentInitialization>::initialize(
                    &self.argv,
                )?,
            provider_filepath:
                <geam_filepath::Component as HostProviderComponentInitialization>::initialize(
                    &self.filepath,
                )?,
            provider_geam_clip_search:
                <geam_clip_cli_native::Component as HostProviderComponentInitialization>::initialize(
                    &self.geam_clip_search,
                )?,
            provider_gleam_regexp:
                <geam_regexp::Component as HostProviderComponentInitialization>::initialize(
                    &self.gleam_regexp,
                )?,
            provider_simplifile:
                <geam_simplifile::Component as HostProviderComponentInitialization>::initialize(
                    &self.simplifile,
                )?,
        })
    }
}

pub struct RunState<Io>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    future: <geam::FutureComponent as HostProviderComponent>::RunState,
    stdlib: <geam::gleam_stdlib::Component<Io> as HostProviderComponent>::RunState,
    provider_argv: <geam_argv::Component as HostProviderComponent>::RunState,
    provider_filepath: <geam_filepath::Component as HostProviderComponent>::RunState,
    provider_geam_clip_search: <geam_clip_cli_native::Component as HostProviderComponent>::RunState,
    provider_gleam_regexp: <geam_regexp::Component as HostProviderComponent>::RunState,
    provider_simplifile: <geam_simplifile::Component as HostProviderComponent>::RunState,
}

impl<Io> RunState<Io>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    pub fn stdlib(&self) -> &geam::gleam_stdlib::GleamStdlibRunState<Io> {
        &self.stdlib
    }

    pub fn stdlib_mut(&mut self) -> &mut geam::gleam_stdlib::GleamStdlibRunState<Io> {
        &mut self.stdlib
    }
}

impl<Io> HostProfile for Profile<Io>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    type ExternalStores = Stores<Io>;
    type RunState = RunState<Io>;
    type ExecutionState = ();
}

impl<Io> HostWorkProfile for Profile<Io>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    type Work = geam::FutureComponent;
}

impl<Io> HostComponentProfile<geam::FutureComponent> for Profile<Io>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    fn component_stores(
        stores: &Self::ExternalStores,
    ) -> &<geam::FutureComponent as HostProviderComponent>::Stores {
        &stores.future
    }

    fn component_state(
        state: &mut Self::RunState,
    ) -> &mut <geam::FutureComponent as HostProviderComponent>::RunState {
        &mut state.future
    }
}

impl<Io> HostComponentProfile<geam::gleam_stdlib::Component<Io>> for Profile<Io>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    fn component_stores(
        stores: &Self::ExternalStores,
    ) -> &<geam::gleam_stdlib::Component<Io> as HostProviderComponent>::Stores {
        &stores.stdlib
    }

    fn component_state(
        state: &mut Self::RunState,
    ) -> &mut <geam::gleam_stdlib::Component<Io> as HostProviderComponent>::RunState {
        &mut state.stdlib
    }
}

impl<Io> HostComponentProfile<geam_argv::Component> for Profile<Io>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    fn component_stores(
        stores: &Self::ExternalStores,
    ) -> &<geam_argv::Component as HostProviderComponent>::Stores {
        &stores.provider_argv
    }

    fn component_state(
        state: &mut Self::RunState,
    ) -> &mut <geam_argv::Component as HostProviderComponent>::RunState {
        &mut state.provider_argv
    }
}

impl<Io> HostComponentProfile<geam_filepath::Component> for Profile<Io>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    fn component_stores(
        stores: &Self::ExternalStores,
    ) -> &<geam_filepath::Component as HostProviderComponent>::Stores {
        &stores.provider_filepath
    }

    fn component_state(
        state: &mut Self::RunState,
    ) -> &mut <geam_filepath::Component as HostProviderComponent>::RunState {
        &mut state.provider_filepath
    }
}

impl<Io> HostComponentProfile<geam_clip_cli_native::Component> for Profile<Io>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    fn component_stores(
        stores: &Self::ExternalStores,
    ) -> &<geam_clip_cli_native::Component as HostProviderComponent>::Stores {
        &stores.provider_geam_clip_search
    }

    fn component_state(
        state: &mut Self::RunState,
    ) -> &mut <geam_clip_cli_native::Component as HostProviderComponent>::RunState {
        &mut state.provider_geam_clip_search
    }
}

impl<Io> HostComponentProfile<geam_regexp::Component> for Profile<Io>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    fn component_stores(
        stores: &Self::ExternalStores,
    ) -> &<geam_regexp::Component as HostProviderComponent>::Stores {
        &stores.provider_gleam_regexp
    }

    fn component_state(
        state: &mut Self::RunState,
    ) -> &mut <geam_regexp::Component as HostProviderComponent>::RunState {
        &mut state.provider_gleam_regexp
    }
}

impl<Io> HostComponentProfile<geam_simplifile::Component> for Profile<Io>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    fn component_stores(
        stores: &Self::ExternalStores,
    ) -> &<geam_simplifile::Component as HostProviderComponent>::Stores {
        &stores.provider_simplifile
    }

    fn component_state(
        state: &mut Self::RunState,
    ) -> &mut <geam_simplifile::Component as HostProviderComponent>::RunState {
        &mut state.provider_simplifile
    }
}

impl<Io> geam::gleam_stdlib::GleamStdlibHostProfile for Profile<Io>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    type Io = Io;
}

pub fn host_providers<Io>() -> Result<ProviderSet<Io>, HostRegistrationError>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    let mut providers =
        <geam::gleam_stdlib::Component<Io> as ComponentRegistration<Profile<Io>>>::providers()?;
    let additional_providers =
        <geam_argv::Component as ComponentRegistration<Profile<Io>>>::providers()?;
    providers.extend(additional_providers);
    let additional_providers =
        <geam_filepath::Component as ComponentRegistration<Profile<Io>>>::providers()?;
    providers.extend(additional_providers);
    let additional_providers =
        <geam_clip_cli_native::Component as ComponentRegistration<Profile<Io>>>::providers()?;
    providers.extend(additional_providers);
    let additional_providers =
        <geam_regexp::Component as ComponentRegistration<Profile<Io>>>::providers()?;
    providers.extend(additional_providers);
    let additional_providers =
        <geam_simplifile::Component as ComponentRegistration<Profile<Io>>>::providers()?;
    providers.extend(additional_providers);
    HostProviderSet::from_providers(providers)
}

pub fn project<Io>() -> HostedProject<Profile<Io>>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    HostedProject::new(
        concat!(env!("CARGO_MANIFEST_DIR"), "/gleam"),
        ROOT_MODULE,
        host_providers::<Io>,
    )
}

#[allow(clippy::type_complexity)]
pub struct Functions {
    pub verify_contracts: Function<(), bool, Function0Input>,
    pub arguments: Function<(), List<StringValue>, Function1Input>,
    pub identity: Function<(), (StringValue, StringValue), Function2Input>,
    pub run: Function<(), Type0, Function3Input>,
    pub main: Function<(), (), Function4Input>,
    pub completed: Function<(Type0,), Result<List<StringValue>, ()>, Function5Input>,
    pub help_text: Function<(Type0,), Result<StringValue, ()>, Function6Input>,
    pub failure_message: Function<(Type0,), Result<StringValue, ()>, Function7Input>,
    pub missing_file: Function<(Type0,), Result<StringValue, ()>, Function8Input>,
    pub invalid_pattern: Function<(Type0,), bool, Function9Input>,
}

pub struct Function0Input;

impl InputShape<()> for Function0Input {}

pub struct Function1Input;

impl InputShape<()> for Function1Input {}

pub struct Function2Input;

impl InputShape<()> for Function2Input {}

pub struct Function3Input;

impl InputShape<()> for Function3Input {}

pub struct Function4Input;

impl InputShape<()> for Function4Input {}

pub struct Function5Input;

impl<Input0> InputShape<(Input0,)> for Function5Input {}

pub struct Function6Input;

impl<Input0> InputShape<(Input0,)> for Function6Input {}

pub struct Function7Input;

impl<Input0> InputShape<(Input0,)> for Function7Input {}

pub struct Function8Input;

impl<Input0> InputShape<(Input0,)> for Function8Input {}

pub struct Function9Input;

impl<Input0> InputShape<(Input0,)> for Function9Input {}

pub fn bind<Io>(
    builder: HostedModuleBuilder<Profile<Io>>,
) -> Result<(HostedModuleBindings<Profile<Io>>, Functions), BindingError>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    let (mut bindings, function_0) =
        builder.function(FunctionDeclaration::new("verify_contracts"))?;
    let function_1 = bindings.function(FunctionDeclaration::new("arguments"))?;
    let function_2 = bindings.function(FunctionDeclaration::new("identity"))?;
    let function_3 = bindings.function(FunctionDeclaration::new("run"))?;
    let function_4 = bindings.function(FunctionDeclaration::new("main"))?;
    let function_5 = bindings.function(FunctionDeclaration::new("completed"))?;
    let function_6 = bindings.function(FunctionDeclaration::new("help_text"))?;
    let function_7 = bindings.function(FunctionDeclaration::new("failure_message"))?;
    let function_8 = bindings.function(FunctionDeclaration::new("missing_file"))?;
    let function_9 = bindings.function(FunctionDeclaration::new("invalid_pattern"))?;
    Ok((
        bindings,
        Functions {
            verify_contracts: function_0.with_input_shape(),
            arguments: function_1.with_input_shape(),
            identity: function_2.with_input_shape(),
            run: function_3.with_input_shape(),
            main: function_4.with_input_shape(),
            completed: function_5.with_input_shape(),
            help_text: function_6.with_input_shape(),
            failure_message: function_7.with_input_shape(),
            missing_file: function_8.with_input_shape(),
            invalid_pattern: function_9.with_input_shape(),
        },
    ))
}
