// Generated by `geam embedding sync`. Do not edit.

use geam::HostComponentProfile;
use geam::HostProfile;
use geam::HostProviderComponent;
use geam::HostProviderComponentInitialization;
use geam::HostProviderComponentRegistration as ComponentRegistration;
use geam::HostProviderConfiguration;
use geam::HostProviderInitializationError;
use geam::HostProviderSet;
use geam::HostRegistrationError;
use geam::HostWorkProfile;

use geam::embedding::BigInt;
use geam::embedding::BindingError;
use geam::embedding::Function;
use geam::embedding::FunctionDeclaration;
use geam::embedding::HostedModuleBindings;
use geam::embedding::HostedModuleBuilder;
use geam::embedding::HostedProject;
use geam::embedding::InputShape;
use geam::embedding::StringValue;
use std::marker::PhantomData;

pub const ROOT_MODULE: &str = "geam_birl_embedding";

pub struct Profile<Io, Source>(PhantomData<fn() -> (Io, Source)>);

pub type ProviderSet<Io, Source> = HostProviderSet<Profile<Io, Source>>;

pub struct Stores<Io, Source>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
    Source: geam::gleam_time::TimeSource,
{
    future: <geam::FutureComponent as HostProviderComponent>::Stores,
    stdlib: <geam::gleam_stdlib::Component<Io> as HostProviderComponent>::Stores,
    time: <geam::gleam_time::Component<Source> as HostProviderComponent>::Stores,
    provider_birl: <geam_birl::Component as HostProviderComponent>::Stores,
    provider_gleam_regexp: <geam_regexp::Component as HostProviderComponent>::Stores,
}

impl<Io, Source> Default for Stores<Io, Source>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
    Source: geam::gleam_time::TimeSource,
{
    fn default() -> Self {
        Self {
            future: Default::default(),
            stdlib: Default::default(),
            time: (),
            provider_birl: Default::default(),
            provider_gleam_regexp: Default::default(),
        }
    }
}

pub struct RunStateInputs<Io, Source>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
    Source: geam::gleam_time::TimeSource,
{
    pub stdlib: geam::gleam_stdlib::GleamStdlibRunState<Io>,
    pub time: Source,
    pub birl: HostProviderConfiguration,
    pub gleam_regexp: HostProviderConfiguration,
}

impl<Io, Source> RunStateInputs<Io, Source>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
    Source: geam::gleam_time::TimeSource,
{
    pub fn initialize(self) -> Result<RunState<Io, Source>, HostProviderInitializationError> {
        Ok(RunState {
            future: (),
            stdlib: self.stdlib,
            time: self.time,
            provider_birl:
                <geam_birl::Component as HostProviderComponentInitialization>::initialize(
                    &self.birl,
                )?,
            provider_gleam_regexp:
                <geam_regexp::Component as HostProviderComponentInitialization>::initialize(
                    &self.gleam_regexp,
                )?,
        })
    }
}

pub struct RunState<Io, Source>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
    Source: geam::gleam_time::TimeSource,
{
    future: <geam::FutureComponent as HostProviderComponent>::RunState,
    stdlib: <geam::gleam_stdlib::Component<Io> as HostProviderComponent>::RunState,
    time: <geam::gleam_time::Component<Source> as HostProviderComponent>::RunState,
    provider_birl: <geam_birl::Component as HostProviderComponent>::RunState,
    provider_gleam_regexp: <geam_regexp::Component as HostProviderComponent>::RunState,
}

impl<Io, Source> RunState<Io, Source>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
    Source: geam::gleam_time::TimeSource,
{
    pub fn stdlib(&self) -> &geam::gleam_stdlib::GleamStdlibRunState<Io> {
        &self.stdlib
    }

    pub fn stdlib_mut(&mut self) -> &mut geam::gleam_stdlib::GleamStdlibRunState<Io> {
        &mut self.stdlib
    }
}

impl<Io, Source> HostProfile for Profile<Io, Source>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
    Source: geam::gleam_time::TimeSource,
{
    type ExternalStores = Stores<Io, Source>;
    type RunState = RunState<Io, Source>;
    type ExecutionState = ();
}

impl<Io, Source> HostWorkProfile for Profile<Io, Source>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
    Source: geam::gleam_time::TimeSource,
{
    type Work = geam::FutureComponent;
}

impl<Io, Source> HostComponentProfile<geam::FutureComponent> for Profile<Io, Source>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
    Source: geam::gleam_time::TimeSource,
{
    fn component_stores(
        stores: &Self::ExternalStores,
    ) -> &<geam::FutureComponent as HostProviderComponent>::Stores {
        &stores.future
    }

    fn component_state(
        state: &mut Self::RunState,
    ) -> &mut <geam::FutureComponent as HostProviderComponent>::RunState {
        &mut state.future
    }
}

impl<Io, Source> HostComponentProfile<geam::gleam_stdlib::Component<Io>> for Profile<Io, Source>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
    Source: geam::gleam_time::TimeSource,
{
    fn component_stores(
        stores: &Self::ExternalStores,
    ) -> &<geam::gleam_stdlib::Component<Io> as HostProviderComponent>::Stores {
        &stores.stdlib
    }

    fn component_state(
        state: &mut Self::RunState,
    ) -> &mut <geam::gleam_stdlib::Component<Io> as HostProviderComponent>::RunState {
        &mut state.stdlib
    }
}

impl<Io, Source> HostComponentProfile<geam::gleam_time::Component<Source>> for Profile<Io, Source>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
    Source: geam::gleam_time::TimeSource,
{
    fn component_stores(
        stores: &Self::ExternalStores,
    ) -> &<geam::gleam_time::Component<Source> as HostProviderComponent>::Stores {
        &stores.time
    }

    fn component_state(
        state: &mut Self::RunState,
    ) -> &mut <geam::gleam_time::Component<Source> as HostProviderComponent>::RunState {
        &mut state.time
    }
}

impl<Io, Source> HostComponentProfile<geam_birl::Component> for Profile<Io, Source>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
    Source: geam::gleam_time::TimeSource,
{
    fn component_stores(
        stores: &Self::ExternalStores,
    ) -> &<geam_birl::Component as HostProviderComponent>::Stores {
        &stores.provider_birl
    }

    fn component_state(
        state: &mut Self::RunState,
    ) -> &mut <geam_birl::Component as HostProviderComponent>::RunState {
        &mut state.provider_birl
    }
}

impl<Io, Source> HostComponentProfile<geam_regexp::Component> for Profile<Io, Source>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
    Source: geam::gleam_time::TimeSource,
{
    fn component_stores(
        stores: &Self::ExternalStores,
    ) -> &<geam_regexp::Component as HostProviderComponent>::Stores {
        &stores.provider_gleam_regexp
    }

    fn component_state(
        state: &mut Self::RunState,
    ) -> &mut <geam_regexp::Component as HostProviderComponent>::RunState {
        &mut state.provider_gleam_regexp
    }
}

impl<Io, Source> geam::gleam_stdlib::GleamStdlibHostProfile for Profile<Io, Source>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
    Source: geam::gleam_time::TimeSource,
{
    type Io = Io;
}

impl<Io, Source> geam::gleam_time::GleamTimeHostProfile for Profile<Io, Source>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
    Source: geam::gleam_time::TimeSource,
{
    type Source = Source;
}

pub fn host_providers<Io, Source>() -> Result<ProviderSet<Io, Source>, HostRegistrationError>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
    Source: geam::gleam_time::TimeSource,
{
    let mut providers = <geam::gleam_stdlib::Component<Io> as ComponentRegistration<
        Profile<Io, Source>,
    >>::providers()?;
    let additional_providers = <geam::gleam_time::Component<Source> as ComponentRegistration<
        Profile<Io, Source>,
    >>::providers()?;
    providers.extend(additional_providers);
    let additional_providers =
        <geam_birl::Component as ComponentRegistration<Profile<Io, Source>>>::providers()?;
    providers.extend(additional_providers);
    let additional_providers =
        <geam_regexp::Component as ComponentRegistration<Profile<Io, Source>>>::providers()?;
    providers.extend(additional_providers);
    HostProviderSet::from_providers(providers)
}

pub fn project<Io, Source>() -> HostedProject<Profile<Io, Source>>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
    Source: geam::gleam_time::TimeSource,
{
    HostedProject::new(
        concat!(env!("CARGO_MANIFEST_DIR"), "/gleam"),
        ROOT_MODULE,
        host_providers::<Io, Source>,
    )
}

#[allow(clippy::type_complexity)]
pub struct Functions {
    pub weekday_at: Function<(BigInt, StringValue), StringValue, Function0Input>,
    pub sampled_order_is_lt: Function<(), bool, Function1Input>,
    pub sampled_difference: Function<(), (BigInt, BigInt), Function2Input>,
    pub observed_timezone: Function<(), Option<StringValue>, Function3Input>,
    pub observed_offset: Function<(), StringValue, Function4Input>,
    pub observed_iso8601: Function<(), StringValue, Function5Input>,
}

pub struct Function0Input;

impl InputShape<(BigInt, StringValue)> for Function0Input {}

pub struct Function1Input;

impl InputShape<()> for Function1Input {}

pub struct Function2Input;

impl InputShape<()> for Function2Input {}

pub struct Function3Input;

impl InputShape<()> for Function3Input {}

pub struct Function4Input;

impl InputShape<()> for Function4Input {}

pub struct Function5Input;

impl InputShape<()> for Function5Input {}

pub fn bind<Io, Source>(
    builder: HostedModuleBuilder<Profile<Io, Source>>,
) -> Result<(HostedModuleBindings<Profile<Io, Source>>, Functions), BindingError>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
    Source: geam::gleam_time::TimeSource,
{
    let (mut bindings, function_0) = builder.function(FunctionDeclaration::new("weekday_at"))?;
    let function_1 = bindings.function(FunctionDeclaration::new("sampled_order_is_lt"))?;
    let function_2 = bindings.function(FunctionDeclaration::new("sampled_difference"))?;
    let function_3 = bindings.function(FunctionDeclaration::new("observed_timezone"))?;
    let function_4 = bindings.function(FunctionDeclaration::new("observed_offset"))?;
    let function_5 = bindings.function(FunctionDeclaration::new("observed_iso8601"))?;
    Ok((
        bindings,
        Functions {
            weekday_at: function_0.with_input_shape(),
            sampled_order_is_lt: function_1.with_input_shape(),
            sampled_difference: function_2.with_input_shape(),
            observed_timezone: function_3.with_input_shape(),
            observed_offset: function_4.with_input_shape(),
            observed_iso8601: function_5.with_input_shape(),
        },
    ))
}
