[package]
name = "geam-houdini-embedding"
version = "0.1.0"
edition = "2024"
rust-version = "1.96"
publish = false

[dependencies]
geam = { git = "https://github.com/panarch/geam.git", rev = "e5e1f5f772c6f48369050bdf3ee35c7a324277e2", default-features = false, features = ["embedding", "tokio", "geam-builtin"] }
geam-houdini = { path = "../.." }
tokio = { version = "1.53.1", default-features = false, features = ["rt"] }

[workspace]
resolver = "3"
