// Generated by `geam embedding sync`. Do not edit.

use geam::HostComponentProfile;
use geam::HostProfile;
use geam::HostProviderComponent;
use geam::HostProviderComponentInitialization;
use geam::HostProviderComponentRegistration as ComponentRegistration;
use geam::HostProviderConfiguration;
use geam::HostProviderInitializationError;
use geam::HostProviderSet;
use geam::HostRegistrationError;
use geam::HostWorkProfile;

use geam::embedding::BigInt;
use geam::embedding::BindingError;
use geam::embedding::Function;
use geam::embedding::FunctionDeclaration;
use geam::embedding::HostedModuleBindings;
use geam::embedding::HostedModuleBuilder;
use geam::embedding::HostedProject;
use geam::embedding::InputShape;

pub const ROOT_MODULE: &str = "geam_term_size_embedding";

pub struct Profile;

pub type ProviderSet = HostProviderSet<Profile>;

#[derive(Default)]
pub struct Stores {
    future: <geam::FutureComponent as HostProviderComponent>::Stores,
    provider_term_size: <geam_term_size::Component as HostProviderComponent>::Stores,
}

pub struct RunStateInputs {
    pub term_size: HostProviderConfiguration,
}

impl RunStateInputs {
    pub fn initialize(self) -> Result<RunState, HostProviderInitializationError> {
        Ok(RunState {
            future: (),
            provider_term_size:
                <geam_term_size::Component as HostProviderComponentInitialization>::initialize(
                    &self.term_size,
                )?,
        })
    }
}

pub struct RunState {
    future: <geam::FutureComponent as HostProviderComponent>::RunState,
    provider_term_size: <geam_term_size::Component as HostProviderComponent>::RunState,
}

impl HostProfile for Profile {
    type ExternalStores = Stores;
    type RunState = RunState;
    type ExecutionState = ();
}

impl HostWorkProfile for Profile {
    type Work = geam::FutureComponent;
}

impl HostComponentProfile<geam::FutureComponent> for Profile {
    fn component_stores(
        stores: &Self::ExternalStores,
    ) -> &<geam::FutureComponent as HostProviderComponent>::Stores {
        &stores.future
    }

    fn component_state(
        state: &mut Self::RunState,
    ) -> &mut <geam::FutureComponent as HostProviderComponent>::RunState {
        &mut state.future
    }
}

impl HostComponentProfile<geam_term_size::Component> for Profile {
    fn component_stores(
        stores: &Self::ExternalStores,
    ) -> &<geam_term_size::Component as HostProviderComponent>::Stores {
        &stores.provider_term_size
    }

    fn component_state(
        state: &mut Self::RunState,
    ) -> &mut <geam_term_size::Component as HostProviderComponent>::RunState {
        &mut state.provider_term_size
    }
}

pub fn host_providers() -> Result<ProviderSet, HostRegistrationError> {
    let providers = <geam_term_size::Component as ComponentRegistration<Profile>>::providers()?;
    HostProviderSet::from_providers(providers)
}

pub fn project() -> HostedProject<Profile> {
    HostedProject::new(
        concat!(env!("CARGO_MANIFEST_DIR"), "/gleam"),
        ROOT_MODULE,
        host_providers,
    )
}

#[allow(clippy::type_complexity)]
pub struct Functions {
    pub get_size: Function<(), Result<(BigInt, BigInt), ()>, Function0Input>,
    pub row_count: Function<(), Result<BigInt, ()>, Function1Input>,
    pub column_count: Function<(), Result<BigInt, ()>, Function2Input>,
}

pub struct Function0Input;

impl InputShape<()> for Function0Input {}

pub struct Function1Input;

impl InputShape<()> for Function1Input {}

pub struct Function2Input;

impl InputShape<()> for Function2Input {}

pub fn bind(
    builder: HostedModuleBuilder<Profile>,
) -> Result<(HostedModuleBindings<Profile>, Functions), BindingError> {
    let (mut bindings, function_0) = builder.function(FunctionDeclaration::new("get_size"))?;
    let function_1 = bindings.function(FunctionDeclaration::new("row_count"))?;
    let function_2 = bindings.function(FunctionDeclaration::new("column_count"))?;
    Ok((
        bindings,
        Functions {
            get_size: function_0.with_input_shape(),
            row_count: function_1.with_input_shape(),
            column_count: function_2.with_input_shape(),
        },
    ))
}
